blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discord Community
    url: https://discord.gg/EKYJAjqGhf
    about: Join our Discord for questions, discussions, and community support
  - name: ğŸ‘” LinkedIn
    url: http://linkedin.com/company/haxtheweb
    about: Connect with us on LinkedIn for professional updates and networking
  - name: ğŸ¦ Follow on X
    url: https://x.com/haxtheweb
    about: Stay updated with the latest news and updates from HAXTheWeb
  - name: ğŸ“š Documentation
    url: https://haxtheweb.org/documentation
    about: Check our comprehensive documentation for guides and tutorials
  - name: ğŸ® Try HAX on hax.cloud
    url: https://hax.cloud/magicscript.html
    about: Explore and experiment with HAXcms, components and more with the magic script